books/urls.py
from django.urls import path
from .views import BooksListView,BookDetailView, AddReviewView,EditReviewView, ConfirmDeleteReviewView,DeleteReviewView

app_name = "books"

urlpatterns = [
    path('', BooksListView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
    path('<int:book_id>/reviews/<int:review_id>/confirm-delete/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(),
         name='delete-review'),
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name="landing_page"),
    path('home/', home_page, name="home_page"),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView,ProfileView, LogoutView, ProfileUpdateView


app_name = "users"
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.png")

users/forms.py
from django import forms
from django.core.mail import send_mail

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'password'
        }

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        # if user.email:
        #     send_mail(
        #         "Welcome to GoodReads Clone",
        #         f"Hi, {{ user.username }}. Welcome to My website",
        #         "majidov_dev@mail.ru",
        #         [user.email],
        #     )

        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = {
            'profile_picture',
            'last_name',
            'first_name',
            'email',
            'username',
        }


# class UserCreateForm(forms.Form):
    # username = forms.CharField(max_length=150)
    # email = forms.EmailField()
    # first_name = forms.CharField(max_length=150)
    # last_name = forms.CharField(max_length=150)
    # password = forms.CharField(max_length=130)
    #
    # def save(self):
    #     username = self.cleaned_data['username']
    #     first_name = self.cleaned_data['first_name']
    #     last_name = self.cleaned_data['last_name']
    #     email = self.cleaned_data['email']
    #     password = self.cleaned_data['password']
    #
    #     user = CustomUser.objects.create(
    #         username=username,
    #         first_name=first_name,
    #         last_name=last_name,
    #         email=email,
    #     )
    #     user.set_password(password)
    #     user.save()


# class UserLoginForm(forms.Form):
#     username = forms.CharField(max_length=150)
#     password = forms.CharField(max_length=150)

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import CustomUser

from users.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, "users/register.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                "form": create_form
            }
            return render(request, "users/register.html", context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        context = {
            "login_form": login_form
        }
        return render(request, "users/login.html", context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        context = {
            "login_form": login_form
        }
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "successfully logged in")
            return redirect("landing_page")
        else:
            return render(request, "users/login.html", context)


class ProfileView(LoginRequiredMixin,View):
    def get(self, request):
        # if not request.user.is_authenticated:
        #     return redirect("users:login")
        return render(request, "users/profile.html", {"user": request.user})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "successfully logged out")
        return redirect("landing_page")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)

        context = {
            "form": user_update_form
        }
        return render(request, 'users/profile_edit.html', context)

    def post(self, request):
        user_update_form = UserUpdateForm(instance=request.user, data=request.POST, files=request.FILES)
        context = {
            "form": user_update_form
        }
        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated your profile")

            return redirect("users:profile")
        return render(request, "users/profile_edit.html", context)

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h1 class="text-center m-3">Login Page</h1>

    <div class="row d-flex justify-content-center">
        <div class="col-4">
            <form method="post">
              {% csrf_token %}
              {{ login_form | crispy }}
              <button class="btn btn-primary">Log In</button>
            </form>
        </div>
    </div>
    <p class="text-center mt-5">Don't have an account yet? <a href="{% url 'users:register' %}">Register</a></p>
{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock title %}
{% block content %}
    <div class="pt-3">
        <h1 class="text-center">Profile Page</h1>
        <!--    request.user's data   -->
        <div class="d-flex justify-content-evenly pt-3 text-center">
            <div>
                <img style="width:250px; height:250px" class="img-fluid mb-3 rounded-3" src="{{ user.profile_picture.url }}" alt="Profile picture">
                <p><b>Username:</b> {{ user.username }}</p>
                <p><b>First Name:</b> {{ user.first_name }}</p>
                <p><b>Last Name:</b> {{ user.last_name }}</p>
                <p><b>Email:</b> {{ user.email }}</p>
                <p><b>Joined:</b> {{ user.date_joined|date:"M d, Y" }}</p>
                <a class="btn btn-outline-warning mt-3" href="{% url 'users:profile-edit' %}">Edit Profile</a>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1 class="text-center m-3">Profile Edit</h1>
    <div class="row d-flex justify-content-center">
        <div class="col-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary">Save changes</button>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock title %}
{% block content %}
    <h1 class="text-center m-3">Register Page</h1>

    <div class="row d-flex justify-content-center">
        <div class="col-4">
            <form method="post" action="{% url 'users:register' %}">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock content %}