books/urls.py
from django.urls import path
from .views import BooksListView,BookDetailView, AddReviewView,EditReviewView, ConfirmDeleteReviewView,DeleteReviewView

app_name = "books"

urlpatterns = [
    path('', BooksListView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
    path('<int:book_id>/reviews/<int:review_id>/confirm-delete/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(),
         name='delete-review'),
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name="landing_page"),
    path('home/', home_page, name="home_page"),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView,ProfileView, LogoutView, ProfileUpdateView


app_name = "users"
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

templates/base.html
{% load static %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:logout' as logout_page_url %}
{% url 'users:login' as login_page_url %}
{% url 'users:register' as register_page_url %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'landing_page' as landing_page_url %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GoodReads Clone{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="{% static 'css/styles.css' %}" type="text/css" rel="stylesheet" >
</head>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light mb-3 sticky-top" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <a class="navbar-brand fs-3" href="{{ landing_page_url }}">GoodReads Clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{ books_page_url }}">Books</a>
            </li>
          </ul>

            <div>
                {% if not request.user.is_authenticated %}
                <a class="btn btn-outline-primary {% if request.path == login_page_url %} active {% endif %}" href="{{ login_page_url }}">Login</a>
                <a class="btn btn-outline-primary {% if request.path == register_page_url %} active {% endif %}" href="{{ register_page_url }}">Register</a>
                {% else %}
                <li class="navbar-nav dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <img style="width:30px; height:30px" class="rounded-circle" src="{{ request.user.profile_picture.url }}" alt="profile pic."> {{ request.user.username }}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item {% if request.path == profile_page_url %} active {% endif %}" href="{{ profile_page_url }}">Profile</a></li>

                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item {% if request.path == logout_page_url %} active {% endif %}" href="{{ logout_page_url }}">Logout</a></li>
                  </ul>
                </li>
                {% endif %}
            </div>
        </div>
      </div>
    </nav>
    {% if messages %}
    <div class="mt-4">
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>

</body>
</html>

templates/home_page.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}
<h2 class="text-center">All reviews</h2>
    <div class="container posts-content">
        <div class="row d-flex">
        {% for review in page_obj %}
            <div class="col-lg-6">
                <div class="card mb-4">
                  <div class="card-body">
                    <div class="media mb-3">
                      <img src="{{ review.user.profile_picture.url }}" style="width:60px; height:60px" class="d-block ui-w-50 rounded-circle" alt="">
                      <div class="media-body ml-3">
                        <b>{{ review.user.username }}</b> {{ review.starts_given }} stars given
                        <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                      </div>
                    </div>
                      <div style="height:8rem">
                          <p>
                          {{ review.comment | truncatechars:250 }}
                          </p>
                      </div>
                      <img src="{{ review.book.cover_picture.url }}" style="width: 100%; height: 40rem" alt="book cover">
                  </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <!--start pagination-->
    <nav class="fixed-bottom d-flex justify-content-center" aria-label="...">
      <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.previous_page_number }}">Prev</a></li>
          {% endif %}

        <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

          {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="{% url 'home_page' %}?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
          {% endif %}
      </ul>
    </nav>
    <!--end pagination-->

{% endblock content %}

templates/landing.html
{% extends 'base.html' %}

{% block content %}
<h1>Landing Page</h1>
<p>
    Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]

    Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.[9]
</p>
<p>
    Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]

    Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.[9]
</p>
<p>
    Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]

    Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.[9]
</p>
<p>
    Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]

    Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.[9]
</p>
{% endblock content %}