books/urls.py
from django.urls import path
from .views import BooksListView,BookDetailView, AddReviewView,EditReviewView, ConfirmDeleteReviewView,DeleteReviewView

app_name = "books"

urlpatterns = [
    path('', BooksListView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/reviews/<int:review_id>/edit/', EditReviewView.as_view(), name='edit-review'),
    path('<int:book_id>/reviews/<int:review_id>/confirm-delete/', ConfirmDeleteReviewView.as_view(), name='confirm-delete-review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/', DeleteReviewView.as_view(),
         name='delete-review'),
]

goodreads/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import landing_page, home_page

urlpatterns = [
    path('', landing_page, name="landing_page"),
    path('home/', home_page, name="home_page"),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator


class Book(models.Model):
    title = models.CharField(max_length=200)  # VARCHAR()
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.png")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def fullname(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.book.title} by {self.author}'


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    starts_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.starts_given} stars for {self.book.title} by {self.user.username}'

books/forms.py
from django import forms
from django.db import models
from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    starts_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:
        model = BookReview
        fields = ('comment', 'starts_given',)

books/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from books.models import Book, BookAuthor, Author, BookReview
from books.forms import BookReviewForm

# class BooksListView(ListView):
#     template_name = "books/list.html"
#     queryset = Book.objects.all()
#     context_object_name = "books"
#     paginate_by = 2

class BooksListView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get("q", '')
        if search_query:
            books = books.filter(title__icontains=search_query)
        paginator = Paginator(books, 4)

        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)
        return render(
            request,
            "books/list.html",
            {
                "page_obj": page_obj,
                "search_query": search_query,
            }
        )


# class BookDetailView(DetailView):
#     template_name = "books/detail.html"
#     pk_url_kwarg = "id"
#     model = Book


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        return render(
            request,
            "books/detail.html",
            {
                "book": book,
                "review_form": review_form,
            }
        )


class AddReviewView(LoginRequiredMixin ,View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                starts_given=review_form.cleaned_data['starts_given'],
                comment=review_form.cleaned_data['comment'],
            )

            return redirect(reverse("books:detail", kwargs={"id":book.id}))
        return render(request, "books/detail.html",   {"review_form": review_form, })


class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)
        context = {
            "book": book,
            "review": review,
            "review_form": review_form
        }
        return render(request, "books/edit_review.html", context)

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse("books:detail", kwargs={"id":book.id}))

        return render(request, "books/edit_review.html")


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        context = {
            "book": book,
            "review": review,
        }
        return render(request, "books/confirm_delete_review.html", context)


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        review.delete()
        messages.success(request, "Successfully deleted Review!")

        return redirect(reverse("books:detail", kwargs={"id": book.id}))

books/templates/books/confirm_delete_review.html
{% extends 'base.html' %}
{% block content %}
<h3>Confirm Delete</h3>
<p>
    <b>Title:</b> {{ book.title }}
</p>
<p>
    <b>Comment:</b> {{ review.comment }}
</p>
<a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-danger">Yes</a>
<a href="{% url 'books:detail' book.id%} " class="btn btn-secondary">No</a>
{% endblock content %}

books/templates/books/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Book Detail{% endblock title %}

{% block content %}
  <h3 class="text-center mb-3">Book Info</h3>
  <hr>
    <div class="row mb-3">
      <h3 class="mb-3">{{ book.title }}
        <span>
          <i class="text-primary">by</i>
          {% for book_author in book.bookauthor_set.all %}
            {% if forloop.last %}
            <i>{{ book_author.author.fullname }}</i>
            {% else %}
            <i>{{ book_author.author.fullname }},</i>
            {% endif %}
          {% endfor %}
        </span>
      </h3>
      <div class="col-2">
          <img style="width:200px; height:300px;" class="rounded-3" src="{{ book.cover_picture.url }}">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary mt-3" data-bs-toggle="modal" data-bs-target="#addReviewModal">
            Add Review
          </button>
      </div>
      <div class="col-6">
          <p>{{ book.description }}</p>
      </div>
    </div>

    {% if book.bookreview_set.exists %}
      <h3 class="text-center" >Reviews</h3> <hr>

      <div class="row d-flex">
        {% for review in book.bookreview_set.all %}
        <div class="col-6">
          <hr>
          <div class="row">
            <div class="col-2">
              <img style="width: 80px; height:80px " class="rounded-3" src="{{ review.user.profile_picture.url }}" alt="profile pic.">
            </div>
            <div class="col-8">
              <div class="d-flex justify-content-between">
                <div>
                  <p class="fs-3 mb-0">{{ review.user.username }} <span class="text-secondary fs-6">{{ review.created_at }}</span></p>
                  <p class="text-secondary fs-5">{{ review.starts_given }} stars given
                    {% if review.user == request.user %}
                    <span class="text-end">
                      <a href="{% url 'books:edit-review' book.id review.id %}"><i class="bi bi-pen"></i></a>|<a href="{% url 'books:confirm-delete-review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                    </span>
                    {% endif %}
                  </p>

                </div>
              </div>
            </div>
          </div>
          <p class="fs-5 fst-italic"> - {{ review.comment }}</p>
        </div>
      {% endfor %}
      </div>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="addReviewModal" tabindex="-1" aria-labelledby="addReviewModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addReviewModalLabel">Review Form</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="post" action="{% url 'books:reviews' book.id %}">
              {% csrf_token %}
              {{ review_form | crispy }}
              <div class="modal-footer">
<!--                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>-->
                <button class="btn btn-primary">Post</button>
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>
{% endblock content %}

books/templates/books/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Edit Review{% endblock %}

{% block content %}
<h3>Edit Review</h3>
<div class="row mb-4">
    <div class="col-6">
        <form action="{% url 'books:edit-review' book.id review.id %}" method="post">
            {% csrf_token %}
            {{ review_form | crispy }}
            <button class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
{% endblock %}

books/templates/books/list.html
{% extends 'base.html' %}

{% block title %}Books LIST{% endblock title %}
{% block content %}
    <div class="row mb-4 d-flex justify-content-between">
        <div class="col-4">
            <h1>Books</h1>
        </div>
        <div class="col-6">
            <form class="d-flex mt-2" method="get">
                <input class="form-control me-3" type="text" placeholder="Enter the book title.." name="q" value="{{ search_query }}">
                <button class="btn btn-primary">Search</button>
            </form>
        </div>
    </div>
    {% if search_query %}
        <p style="font-size: 28px" class="text-center m-4">Result for query: ...<span class="text-primary">{{ search_query }}</span>...</p>
    {% endif %}
    {% if page_obj %}
        <div class="row d-flex">
        {% for book in page_obj.object_list %}
            <div class="col-6 mb-3">
                <div class="row">
                    <div class="col-3">
                        <img style="width:150px; height:200px;" class="rounded-3" src="{{ book.cover_picture.url }}">
                    </div>
                    <div class="col-8">
                        <h3><a href="{% url 'books:detail' book.pk %}">{{ book.title }}</a></h3>
                        <p>{{ book.description| truncatewords:50 }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        <!--start pagination-->
        <nav class="fixed-bottom d-flex justify-content-center" aria-label="...">
          <ul class="pagination">
              {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.previous_page_number }}">Prev</a></li>
              {% endif %}

            <li class="page-item active" aria-current="page"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

              {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'books:list' %}?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
              {% endif %}
          </ul>
        </nav>
        <!--end pagination-->
    {% else %}
        No books found.
    {% endif %}
{% endblock content %}